[LINUX] Made libcdio be compiled alongside XBMC instead of using precompiled versions, Much better for other distros
git-svn-id: https://xbmc.svn.sourceforge.net/svnroot/xbmc/branches/linuxport/XBMC@16736 568bbfeb-2a22-0410-94d2-cc84cf5bfa90

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -14069,6 +14069,8 @@ ac_config_files="$ac_config_files Makefile Makefile.include xbmc/lib/libPython/l
 
 
 
+
+
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -15617,6 +15619,24 @@ echo "$as_me: error: Submodule xbmc/screensavers/rsxs-0.9/ failed to configure" 
 else
   { { echo "$as_me:$LINENO: error: Submodule xbmc/screensavers/rsxs-0.9/ doesn't exist" >&5
 echo "$as_me: error: Submodule xbmc/screensavers/rsxs-0.9/ doesn't exist" >&2;}
+   { (exit 1); exit 1; }; }
+fi;
+
+
+if [ -d xbmc/lib/libcdio/libcdio ]; then
+  pushd xbmc/lib/libcdio/libcdio
+  ./configure --enable-cddb
+  if [ $? -ne 0 ]; then
+    popd
+    { { echo "$as_me:$LINENO: error: Submodule xbmc/lib/libcdio/libcdio failed to configure" >&5
+echo "$as_me: error: Submodule xbmc/lib/libcdio/libcdio failed to configure" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    popd
+  fi;
+else
+  { { echo "$as_me:$LINENO: error: Submodule xbmc/lib/libcdio/libcdio doesn't exist" >&5
+echo "$as_me: error: Submodule xbmc/lib/libcdio/libcdio doesn't exist" >&2;}
    { (exit 1); exit 1; }; }
 fi;
 
