added: support for Wii remote (thanks to Topfs2)
git-svn-id: https://xbmc.svn.sourceforge.net/svnroot/xbmc/branches/linuxport/XBMC@11428 568bbfeb-2a22-0410-94d2-cc84cf5bfa90

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1267,6 +1267,7 @@ Optional Features:
   --enable-xrandr         enable XRandR support (default is yes)
   --enable-mms            enable libmms support (default is yes)
   --enable-gmyth          enable gmyth support (default is no)
+  --enable-cwiid          enable Wii remote support (default is no)
 
 Some influential environment variables:
   CXX         C++ compiler command
@@ -1771,6 +1772,14 @@ if test "${enable_gmyth+set}" = set; then
   enableval=$enable_gmyth; use_gmyth=$enableval
 else
   use_gmyth=no
+fi
+
+
+# Check whether --enable-cwiid was given.
+if test "${enable_cwiid+set}" = set; then
+  enableval=$enable_cwiid; use_cwiid=$enableval
+else
+  use_cwiid=no
 fi
 
 
@@ -4882,6 +4891,80 @@ fi
 else
   { echo "$as_me:$LINENO: result: == GMyth support disabled. ==" >&5
 echo "${ECHO_T}== GMyth support disabled. ==" >&6; }
+fi
+
+if test "$use_cwiid" = "yes"; then
+
+{ echo "$as_me:$LINENO: checking for main in -lcwiid" >&5
+echo $ECHO_N "checking for main in -lcwiid... $ECHO_C" >&6; }
+if test "${ac_cv_lib_cwiid_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lcwiid  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+return main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_cwiid_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_cwiid_main=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_cwiid_main" >&5
+echo "${ECHO_T}$ac_cv_lib_cwiid_main" >&6; }
+if test $ac_cv_lib_cwiid_main = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBCWIID 1
+_ACEOF
+
+  LIBS="-lcwiid $LIBS"
+
+else
+  use_cwiid="no";{ echo "$as_me:$LINENO: result: == Could not find libcwiid. Wii remote support disabled. ==" >&5
+echo "${ECHO_T}== Could not find libcwiid. Wii remote support disabled. ==" >&6; }
+fi
+
+else
+  { echo "$as_me:$LINENO: result: == Wii remote support disabled. ==" >&5
+echo "${ECHO_T}== Wii remote support disabled. ==" >&6; }
 fi
 
 
@@ -11897,6 +11980,12 @@ else
   final_message="$final_message\n  GMyth:\tNo"
 fi
 
+if test "$use_cwiid" = "yes"; then
+  final_message="$final_message\n  Wii Remote:\tYes"
+  SDL_DEFINES="$SDL_DEFINES -DHAS_CWIID"
+else
+  final_message="$final_message\n  Wii Remote:\tNo"
+fi
 
 if test -d "/usr/include/lzo"; then
   LZO_INCLUDES="-I/usr/include/lzo"
