fixed check for lzo and lzo2 in configure.in script. thanks tssgery.
git-svn-id: https://xbmc.svn.sourceforge.net/svnroot/xbmc/branches/linuxport/XBMC@10831 568bbfeb-2a22-0410-94d2-cc84cf5bfa90

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3944,6 +3944,71 @@ echo "$as_me: error: == Could not find a required library. Please see README.lin
    { (exit 1); exit 1; }; }
 fi
 
+#AC_CHECK_LIB([lzo], [main],, AC_MSG_ERROR(== Could not find liblzo))
+
+{ echo "$as_me:$LINENO: checking for main in -llzo2" >&5
+echo $ECHO_N "checking for main in -llzo2... $ECHO_C" >&6; }
+if test "${ac_cv_lib_lzo2_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-llzo2  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+return main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_lzo2_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_lzo2_main=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_lzo2_main" >&5
+echo "${ECHO_T}$ac_cv_lib_lzo2_main" >&6; }
+if test $ac_cv_lib_lzo2_main = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBLZO2 1
+_ACEOF
+
+  LIBS="-llzo2 $LIBS"
+
+else
 
 { echo "$as_me:$LINENO: checking for main in -llzo" >&5
 echo $ECHO_N "checking for main in -llzo... $ECHO_C" >&6; }
@@ -4008,14 +4073,14 @@ _ACEOF
   LIBS="-llzo $LIBS"
 
 else
-  { { echo "$as_me:$LINENO: error: == Could not find liblzo" >&5
-echo "$as_me: error: == Could not find liblzo" >&2;}
+  { { echo "$as_me:$LINENO: error: == Could not find either liblzo or liblzo2 - one of these must be present" >&5
+echo "$as_me: error: == Could not find either liblzo or liblzo2 - one of these must be present" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-#AC_CHECK_LIB([lzo], [main],,
-#  AC_CHECK_LIB([lzo2], [main],, AC_MSG_ERROR(== Could not find either liblzo or liblzo2 - one of these must be present))
-#  )
+
+fi
+
 
 { echo "$as_me:$LINENO: checking for main in -lsmbclient" >&5
 echo $ECHO_N "checking for main in -lsmbclient... $ECHO_C" >&6; }
