changed: simplify command to configure submodule by using autoconf macro.
git-svn-id: https://xbmc.svn.sourceforge.net/svnroot/xbmc/branches/linuxport/XBMC@14258 568bbfeb-2a22-0410-94d2-cc84cf5bfa90

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13174,6 +13174,36 @@ ac_config_files="$ac_config_files Makefile Makefile.include xbmc/lib/libPython/l
 
 
 
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -14288,20 +14318,282 @@ _ACEOF
 chmod +x $CONFIG_STATUS
 ac_clean_files=$ac_clean_files_save
 
-pushd xbmc/lib/libPython/Python && ./configure --enable-ipv6 --enable-unicode=ucs4 --without-cxx --enable-shared --prefix=`pwd`/../linux/python-lib MACOSX_DEPLOYMENT_TARGET=10.5 && sed -i -e "s/define HAVE_GETC_UNLOCKED 1/undef HAVE_GETC_UNLOCKED/" pyconfig.h && cp pyconfig.h Include && popd
-pushd xbmc/cores/paplayer/MPCCodec && ./configure && popd
-pushd xbmc/cores/paplayer/MP3Codec/libmad-0.15.1b && ./configure CFLAGS="-O3 -fPIC" CXXFLAGS="-O3 -fPIC" && popd
-pushd xbmc/cores/paplayer/flac-1.2.1 && ./configure -C --with-pic --disable-asm-optimizations CC="$CC" CXX="$CXX" && popd
-pushd xbmc/cores/paplayer/vorbisfile/libvorbis && ./configure && popd
-pushd xbmc/cores/paplayer/vorbisfile/ogg && ./configure && popd
-pushd xbmc/cores/dvdplayer/Codecs/ffmpeg && ./configure --extra-cflags="-D_XBOX"  --enable-shared --enable-postproc --enable-gpl --disable-static --disable-vhook --enable-swscale --enable-protocol=http --disable-altivec --disable-ipv6 --enable-pthreads --disable-debug && popd
-pushd xbmc/cores/dvdplayer/Codecs/libdts && ./configure --disable-oss --disable-solaris-adio --disable-al-audio --disable-win CFLAGS="-fPIC" && popd
-pushd xbmc/cores/dvdplayer/Codecs/libDVDCSS && ./configure --enable-static --disable-shared --with-pic && popd
-pushd xbmc/cores/dvdplayer/Codecs/libdvdnav && ./configure --enable-static --disable-shared --with-pic && popd
-pushd xbmc/cores/dvdplayer/Codecs/libfaad2 && autoreconf -v -i -f && ./configure --with-pic --with-mp4v2 && popd
-pushd xbmc/cores/dvdplayer/Codecs/libmad && ./configure && popd
-pushd xbmc/lib/cximage-6.0/zlib && CFLAGS=-fPIC ./configure && popd
-pushd xbmc/lib/libass/ && CFLAGS=-fPIC ./configure && popd
+xbmc/lib/libPython/Python
+
+if [ -d xbmc/cores/paplayer/MPCCodec ]; then
+  pushd xbmc/cores/paplayer/MPCCodec
+  ./configure
+  if [ $? -ne 0 ]; then
+    popd
+    { { echo "$as_me:$LINENO: error: Submodule xbmc/cores/paplayer/MPCCodec failed to configure" >&5
+echo "$as_me: error: Submodule xbmc/cores/paplayer/MPCCodec failed to configure" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    popd
+  fi;
+else
+  { { echo "$as_me:$LINENO: error: Submodule xbmc/cores/paplayer/MPCCodec doesn't exist" >&5
+echo "$as_me: error: Submodule xbmc/cores/paplayer/MPCCodec doesn't exist" >&2;}
+   { (exit 1); exit 1; }; }
+fi;
+
+
+if [ -d xbmc/cores/paplayer/MP3Codec/libmad-0.15.1b ]; then
+  pushd xbmc/cores/paplayer/MP3Codec/libmad-0.15.1b
+  ./configure CFLAGS="-O3 -fPIC" CXXFLAGS="-O3 -fPIC"
+  if [ $? -ne 0 ]; then
+    popd
+    { { echo "$as_me:$LINENO: error: Submodule xbmc/cores/paplayer/MP3Codec/libmad-0.15.1b failed to configure" >&5
+echo "$as_me: error: Submodule xbmc/cores/paplayer/MP3Codec/libmad-0.15.1b failed to configure" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    popd
+  fi;
+else
+  { { echo "$as_me:$LINENO: error: Submodule xbmc/cores/paplayer/MP3Codec/libmad-0.15.1b doesn't exist" >&5
+echo "$as_me: error: Submodule xbmc/cores/paplayer/MP3Codec/libmad-0.15.1b doesn't exist" >&2;}
+   { (exit 1); exit 1; }; }
+fi;
+
+
+if [ -d xbmc/cores/paplayer/flac-1.2.1 ]; then
+  pushd xbmc/cores/paplayer/flac-1.2.1
+
+  ./configure -C \
+    --with-pic \
+    --disable-asm-optimizations \
+    CC="$CC" \
+    CXX="$CXX"
+
+  if [ $? -ne 0 ]; then
+    popd
+    { { echo "$as_me:$LINENO: error: Submodule xbmc/cores/paplayer/flac-1.2.1 failed to configure" >&5
+echo "$as_me: error: Submodule xbmc/cores/paplayer/flac-1.2.1 failed to configure" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    popd
+  fi;
+else
+  { { echo "$as_me:$LINENO: error: Submodule xbmc/cores/paplayer/flac-1.2.1 doesn't exist" >&5
+echo "$as_me: error: Submodule xbmc/cores/paplayer/flac-1.2.1 doesn't exist" >&2;}
+   { (exit 1); exit 1; }; }
+fi;
+
+
+if [ -d xbmc/cores/paplayer/vorbisfile/libvorbis ]; then
+  pushd xbmc/cores/paplayer/vorbisfile/libvorbis
+  ./configure && popd
+  if [ $? -ne 0 ]; then
+    popd
+    { { echo "$as_me:$LINENO: error: Submodule xbmc/cores/paplayer/vorbisfile/libvorbis failed to configure" >&5
+echo "$as_me: error: Submodule xbmc/cores/paplayer/vorbisfile/libvorbis failed to configure" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    popd
+  fi;
+else
+  { { echo "$as_me:$LINENO: error: Submodule xbmc/cores/paplayer/vorbisfile/libvorbis doesn't exist" >&5
+echo "$as_me: error: Submodule xbmc/cores/paplayer/vorbisfile/libvorbis doesn't exist" >&2;}
+   { (exit 1); exit 1; }; }
+fi;
+
+
+if [ -d xbmc/cores/paplayer/vorbisfile/ogg ]; then
+  pushd xbmc/cores/paplayer/vorbisfile/ogg
+  ./configure
+  if [ $? -ne 0 ]; then
+    popd
+    { { echo "$as_me:$LINENO: error: Submodule xbmc/cores/paplayer/vorbisfile/ogg failed to configure" >&5
+echo "$as_me: error: Submodule xbmc/cores/paplayer/vorbisfile/ogg failed to configure" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    popd
+  fi;
+else
+  { { echo "$as_me:$LINENO: error: Submodule xbmc/cores/paplayer/vorbisfile/ogg doesn't exist" >&5
+echo "$as_me: error: Submodule xbmc/cores/paplayer/vorbisfile/ogg doesn't exist" >&2;}
+   { (exit 1); exit 1; }; }
+fi;
+
+
+if [ -d xbmc/cores/dvdplayer/Codecs/ffmpeg ]; then
+  pushd xbmc/cores/dvdplayer/Codecs/ffmpeg
+
+  ./configure --extra-cflags="-D_XBOX" \
+    --enable-shared \
+    --enable-postproc \
+    --enable-gpl \
+    --disable-static \
+    --disable-vhook \
+    --enable-swscale \
+    --enable-protocol=http \
+    --disable-altivec \
+    --disable-ipv6 \
+    --enable-pthreads \
+    --disable-debug
+
+  if [ $? -ne 0 ]; then
+    popd
+    { { echo "$as_me:$LINENO: error: Submodule xbmc/cores/dvdplayer/Codecs/ffmpeg failed to configure" >&5
+echo "$as_me: error: Submodule xbmc/cores/dvdplayer/Codecs/ffmpeg failed to configure" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    popd
+  fi;
+else
+  { { echo "$as_me:$LINENO: error: Submodule xbmc/cores/dvdplayer/Codecs/ffmpeg doesn't exist" >&5
+echo "$as_me: error: Submodule xbmc/cores/dvdplayer/Codecs/ffmpeg doesn't exist" >&2;}
+   { (exit 1); exit 1; }; }
+fi;
+
+
+if [ -d xbmc/cores/dvdplayer/Codecs/libdts ]; then
+  pushd xbmc/cores/dvdplayer/Codecs/libdts
+
+  ./configure \
+    --disable-oss \
+    --disable-solaris-adio \
+    --disable-al-audio \
+    --disable-win \
+    CFLAGS="-fPIC"
+
+  if [ $? -ne 0 ]; then
+    popd
+    { { echo "$as_me:$LINENO: error: Submodule xbmc/cores/dvdplayer/Codecs/libdts failed to configure" >&5
+echo "$as_me: error: Submodule xbmc/cores/dvdplayer/Codecs/libdts failed to configure" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    popd
+  fi;
+else
+  { { echo "$as_me:$LINENO: error: Submodule xbmc/cores/dvdplayer/Codecs/libdts doesn't exist" >&5
+echo "$as_me: error: Submodule xbmc/cores/dvdplayer/Codecs/libdts doesn't exist" >&2;}
+   { (exit 1); exit 1; }; }
+fi;
+
+
+if [ -d xbmc/cores/dvdplayer/Codecs/libDVDCSS ]; then
+  pushd xbmc/cores/dvdplayer/Codecs/libDVDCSS
+
+  ./configure \
+    --enable-static \
+    --disable-shared \
+    --with-pic
+
+  if [ $? -ne 0 ]; then
+    popd
+    { { echo "$as_me:$LINENO: error: Submodule xbmc/cores/dvdplayer/Codecs/libDVDCSS failed to configure" >&5
+echo "$as_me: error: Submodule xbmc/cores/dvdplayer/Codecs/libDVDCSS failed to configure" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    popd
+  fi;
+else
+  { { echo "$as_me:$LINENO: error: Submodule xbmc/cores/dvdplayer/Codecs/libDVDCSS doesn't exist" >&5
+echo "$as_me: error: Submodule xbmc/cores/dvdplayer/Codecs/libDVDCSS doesn't exist" >&2;}
+   { (exit 1); exit 1; }; }
+fi;
+
+
+if [ -d xbmc/cores/dvdplayer/Codecs/libdvdnav ]; then
+  pushd xbmc/cores/dvdplayer/Codecs/libdvdnav
+
+  ./configure \
+    --enable-static \
+    --disable-shared \
+    --with-pic
+
+  if [ $? -ne 0 ]; then
+    popd
+    { { echo "$as_me:$LINENO: error: Submodule xbmc/cores/dvdplayer/Codecs/libdvdnav failed to configure" >&5
+echo "$as_me: error: Submodule xbmc/cores/dvdplayer/Codecs/libdvdnav failed to configure" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    popd
+  fi;
+else
+  { { echo "$as_me:$LINENO: error: Submodule xbmc/cores/dvdplayer/Codecs/libdvdnav doesn't exist" >&5
+echo "$as_me: error: Submodule xbmc/cores/dvdplayer/Codecs/libdvdnav doesn't exist" >&2;}
+   { (exit 1); exit 1; }; }
+fi;
+
+
+if [ -d xbmc/cores/dvdplayer/Codecs/libfaad2 ]; then
+  pushd xbmc/cores/dvdplayer/Codecs/libfaad2
+
+  autoreconf -v -i -f &&
+  ./configure \
+    --with-pic \
+    --with-mp4v2
+
+  if [ $? -ne 0 ]; then
+    popd
+    { { echo "$as_me:$LINENO: error: Submodule xbmc/cores/dvdplayer/Codecs/libfaad2 failed to configure" >&5
+echo "$as_me: error: Submodule xbmc/cores/dvdplayer/Codecs/libfaad2 failed to configure" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    popd
+  fi;
+else
+  { { echo "$as_me:$LINENO: error: Submodule xbmc/cores/dvdplayer/Codecs/libfaad2 doesn't exist" >&5
+echo "$as_me: error: Submodule xbmc/cores/dvdplayer/Codecs/libfaad2 doesn't exist" >&2;}
+   { (exit 1); exit 1; }; }
+fi;
+
+
+if [ -d xbmc/cores/dvdplayer/Codecs/libmad ]; then
+  pushd xbmc/cores/dvdplayer/Codecs/libmad
+  ./configure
+  if [ $? -ne 0 ]; then
+    popd
+    { { echo "$as_me:$LINENO: error: Submodule xbmc/cores/dvdplayer/Codecs/libmad failed to configure" >&5
+echo "$as_me: error: Submodule xbmc/cores/dvdplayer/Codecs/libmad failed to configure" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    popd
+  fi;
+else
+  { { echo "$as_me:$LINENO: error: Submodule xbmc/cores/dvdplayer/Codecs/libmad doesn't exist" >&5
+echo "$as_me: error: Submodule xbmc/cores/dvdplayer/Codecs/libmad doesn't exist" >&2;}
+   { (exit 1); exit 1; }; }
+fi;
+
+
+if [ -d xbmc/lib/cximage-6.0/zlib ]; then
+  pushd xbmc/lib/cximage-6.0/zlib
+  CFLAGS=-fPIC ./configure
+  if [ $? -ne 0 ]; then
+    popd
+    { { echo "$as_me:$LINENO: error: Submodule xbmc/lib/cximage-6.0/zlib failed to configure" >&5
+echo "$as_me: error: Submodule xbmc/lib/cximage-6.0/zlib failed to configure" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    popd
+  fi;
+else
+  { { echo "$as_me:$LINENO: error: Submodule xbmc/lib/cximage-6.0/zlib doesn't exist" >&5
+echo "$as_me: error: Submodule xbmc/lib/cximage-6.0/zlib doesn't exist" >&2;}
+   { (exit 1); exit 1; }; }
+fi;
+
+
+if [ -d xbmc/lib/libass ]; then
+  pushd xbmc/lib/libass
+  CFLAGS=-fPIC ./configure
+  if [ $? -ne 0 ]; then
+    popd
+    { { echo "$as_me:$LINENO: error: Submodule xbmc/lib/libass failed to configure" >&5
+echo "$as_me: error: Submodule xbmc/lib/libass failed to configure" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    popd
+  fi;
+else
+  { { echo "$as_me:$LINENO: error: Submodule xbmc/lib/libass doesn't exist" >&5
+echo "$as_me: error: Submodule xbmc/lib/libass doesn't exist" >&2;}
+   { (exit 1); exit 1; }; }
+fi;
+
 
 # configure is writing to config.log, and then calls config.status.
 # config.status does its own redirection, appending to config.log.
