added: Compile liba52 and libao from sources on linux. Successfully increases configure time by 2s and compile time by 5s!
git-svn-id: https://xbmc.svn.sourceforge.net/svnroot/xbmc/branches/linuxport/XBMC@15227 568bbfeb-2a22-0410-94d2-cc84cf5bfa90

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13693,6 +13693,9 @@ ac_config_files="$ac_config_files Makefile Makefile.include xbmc/lib/libPython/l
 
 
 
+
+
+
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -15061,6 +15064,31 @@ echo "$as_me: error: Submodule xbmc/cores/dvdplayer/Codecs/libfaad2 failed to co
 else
   { { echo "$as_me:$LINENO: error: Submodule xbmc/cores/dvdplayer/Codecs/libfaad2 doesn't exist" >&5
 echo "$as_me: error: Submodule xbmc/cores/dvdplayer/Codecs/libfaad2 doesn't exist" >&2;}
+   { (exit 1); exit 1; }; }
+fi;
+
+
+if [ -d xbmc/cores/dvdplayer/Codecs/liba52 ]; then
+  pushd xbmc/cores/dvdplayer/Codecs/liba52
+
+  ./configure \
+  --with-pic \
+  --disable-oss \
+  --disable-solaris-audio \
+  --disable-win \
+  --disable-al-audio
+
+  if [ $? -ne 0 ]; then
+    popd
+    { { echo "$as_me:$LINENO: error: Submodule xbmc/cores/dvdplayer/Codecs/liba52 failed to configure" >&5
+echo "$as_me: error: Submodule xbmc/cores/dvdplayer/Codecs/liba52 failed to configure" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    popd
+  fi;
+else
+  { { echo "$as_me:$LINENO: error: Submodule xbmc/cores/dvdplayer/Codecs/liba52 doesn't exist" >&5
+echo "$as_me: error: Submodule xbmc/cores/dvdplayer/Codecs/liba52 doesn't exist" >&2;}
    { (exit 1); exit 1; }; }
 fi;
 
