fixed: configure script missed a couple headers on some distros (thanks to oldnemesis).
git-svn-id: https://xbmc.svn.sourceforge.net/svnroot/xbmc/branches/linuxport/XBMC@16452 568bbfeb-2a22-0410-94d2-cc84cf5bfa90

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4494,6 +4494,284 @@ echo "$as_me: error: libmad is required. Please see README.linux" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
+if test "${ac_cv_header_mad_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for mad.h" >&5
+echo $ECHO_N "checking for mad.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_mad_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_mad_h" >&5
+echo "${ECHO_T}$ac_cv_header_mad_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking mad.h usability" >&5
+echo $ECHO_N "checking mad.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <mad.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking mad.h presence" >&5
+echo $ECHO_N "checking mad.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <mad.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: mad.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: mad.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: mad.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: mad.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: mad.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: mad.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: mad.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: mad.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: mad.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: mad.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: mad.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: mad.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: mad.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: mad.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: mad.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: mad.h: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## ---------------------------- ##
+## Report this to bugs@xbmc.org ##
+## ---------------------------- ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for mad.h" >&5
+echo $ECHO_N "checking for mad.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_mad_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_mad_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_mad_h" >&5
+echo "${ECHO_T}$ac_cv_header_mad_h" >&6; }
+
+fi
+if test $ac_cv_header_mad_h = yes; then
+  :
+else
+  { { echo "$as_me:$LINENO: error: libmad is required. Please see README.linux" >&5
+echo "$as_me: error: libmad is required. Please see README.linux" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+if test "${ac_cv_header_jpegint_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for jpegint.h" >&5
+echo $ECHO_N "checking for jpegint.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_jpegint_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_jpegint_h" >&5
+echo "${ECHO_T}$ac_cv_header_jpegint_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking jpegint.h usability" >&5
+echo $ECHO_N "checking jpegint.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <jpegint.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking jpegint.h presence" >&5
+echo $ECHO_N "checking jpegint.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <jpegint.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: jpegint.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: jpegint.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: jpegint.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: jpegint.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: jpegint.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: jpegint.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: jpegint.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: jpegint.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: jpegint.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: jpegint.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: jpegint.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: jpegint.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: jpegint.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: jpegint.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: jpegint.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: jpegint.h: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## ---------------------------- ##
+## Report this to bugs@xbmc.org ##
+## ---------------------------- ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for jpegint.h" >&5
+echo $ECHO_N "checking for jpegint.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_jpegint_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_jpegint_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_jpegint_h" >&5
+echo "${ECHO_T}$ac_cv_header_jpegint_h" >&6; }
+
+fi
+if test $ac_cv_header_jpegint_h = yes; then
+  :
+else
+  { { echo "$as_me:$LINENO: error: jpegint is required. Please see README.linux" >&5
+echo "$as_me: error: jpegint is required. Please see README.linux" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
 if test "$host_vendor" != "apple"; then
 
 { echo "$as_me:$LINENO: checking for main in -ltre" >&5
