[DSPlayer] merged from trunk revs r29721:30159 (part 3)
git-svn-id: https://xbmc.svn.sourceforge.net/svnroot/xbmc/branches/dsplayer@30162 568bbfeb-2a22-0410-94d2-cc84cf5bfa90

diff --git a/tools/Linux/packaging/debian/var_info b/tools/Linux/packaging/debian/var_info
--- a/tools/Linux/packaging/debian/var_info
+++ b/tools/Linux/packaging/debian/var_info
@@ -10,7 +10,7 @@ BUILD_DEPENDS="debhelper (>= 7.0.50), python-support, cmake,
  libmysqlclient-dev, libasound-dev, libpng12-dev | libpng-dev, libpcre3-dev,
  liblzo2-dev, libcdio-dev, libsdl-dev, libsdl-image1.2-dev, libsdl-mixer1.2-dev,
  libenca-dev, libjasper-dev, libxt-dev, libxtst-dev, libxmu-dev,
- libxinerama-dev, libcurl-dev | libcurl4-gnutls-dev, libdbus-1-dev,
+ libxinerama-dev, libcurl4-openssl-dev | libcurl-dev, libdbus-1-dev,
  libhal-storage-dev, libhal-dev, libpulse-dev, libavahi-common-dev,
  libavahi-client-dev, libxrandr-dev, libavcodec-dev, libavformat-dev,
  libavutil-dev, libpostproc-dev, libswscale-dev, liba52-dev, libdts-dev,
@@ -30,13 +30,13 @@ case "$1" in
         printf "$BUILD_DEPENDS"
         ;;
     LIBCURL_DEPENDS)
-	LIBCURL_DEPENDS=$(cat /var/lib/dpkg/info/libcurl3.shlibs | \
-	    sed 's/^[^[:space:]]\+\?[[:space:]]\+\?[^[:space:]]\+\?[[:space:]]\+\?\(.*\)$/\1/')
-	if [ $(lsb_release -cs) = "hardy" ]; then
-	    LIBCURL_DEPENDS="libcurl3"
-	fi
-	printf "$LIBCURL_DEPENDS"
-	;;
+        LIBCURL_DEPENDS=$(cat /var/lib/dpkg/info/libcurl3.shlibs | \
+          sed 's/^[^[:space:]]\+\?[[:space:]]\+\?[^[:space:]]\+\?[[:space:]]\+\?\(.*\)$/\1/')
+        if [ $(lsb_release -cs) = "hardy" ]; then
+          LIBCURL_DEPENDS="libcurl3"
+        fi
+        printf "$LIBCURL_DEPENDS"
+        ;;
     XBMC_LIVE_DEPENDS)
         XBMC_LIVE_DEPENDS="xbmc-standalone (= \${binary:Version}),
          policykit,
@@ -54,9 +54,27 @@ case "$1" in
         fi
         if [ $(lsb_release -cs) = "lucid" ]; then
             XBMC_LIVE_DEPENDS="$XBMC_LIVE_DEPENDS
-          mkpasswd,"
+         mkpasswd,"
         fi
         printf "$XBMC_LIVE_DEPENDS"
+        ;;
+    LIBVDPAU_DEPENDS)
+        LIBVDPAU_DEPENDS=""
+        if [ -r /var/lib/dpkg/info/libvdpau*.shlibs ]; then
+          LIBVDPAU_DEPENDS=$(cat /var/lib/dpkg/info/libvdpau*.shlibs | \
+          grep 'libvdpau ' | \
+          sed 's/^[^[:space:]]\+\?[[:space:]]\+\?[^[:space:]]\+\?[[:space:]]\+\?\(.*\)$/\1/')
+        elif [ -r /var/lib/dpkg/info/nvidia-185-libvdpau.shlibs ]; then
+          LIBVDPAU_DEPENDS=$(cat /var/lib/dpkg/info/nvidia-185-libvdpau.shlibs | \
+          grep 'libvdpau ' | \
+          sed 's/^[^[:space:]]\+\?[[:space:]]\+\?[^[:space:]]\+\?[[:space:]]\+\?\(.*\)$/\1/')
+        fi
+        if [ -z $LIBVDPAU_DEPENDS ]; then
+          echo "Error in getting shlibs information for libvdpau."
+          exit 1
+        fi
+        printf "$LIBVDPAU_DEPENDS"
+        ;;
 esac
 
 exit 0
