[crystalhd] merge r25149:25219 from trunk
git-svn-id: https://xbmc.svn.sourceforge.net/svnroot/xbmc/branches/crystalhd@25221 568bbfeb-2a22-0410-94d2-cc84cf5bfa90

diff --git a/tools/Linux/packaging/debian/xbmc-live.postrm b/tools/Linux/packaging/debian/xbmc-live.postrm
--- a/tools/Linux/packaging/debian/xbmc-live.postrm
+++ b/tools/Linux/packaging/debian/xbmc-live.postrm
@@ -4,9 +4,39 @@
 # see: dh_installdeb(1)
 
 set -e
-if [ "$1" = "purge" ]                                                    
-then                            
-	sed -i -e "/XBMC/d" /etc/sudoers
+if [ "$1" = "purge" ]; then
+	SUDOERS="$(cat /etc/sudoers)"
+
+	SUDOERS_TEMPFILE=$(mktemp -q)
+
+	# Check if there are XBMC specific entries in /etc/sudoers and remove
+	# them if so. This makes use of perl for checking and writing a sudoers
+	# file
+	if perl -e '$sudoers=$ARGV[0]; $entries=$ARGV[1];' \
+	    -e '($sudoers =~ m/$entries/ms) ? exit 0 : exit 1;' \
+	    "$SUDOERS" "### XBMC-specific configuration ###"; then
+
+	    # First write a sudoers file to a tempfile.
+	    perl -e '$sudoers=$ARGV[0];' \
+		-e '$sudoers =~ s/\Q### XBMC-specific configuration ###\E\n//g;' \
+		-e '$sudoers =~ s/\n.*# XBMC.*//g;' \
+		-e 'chomp $sudoers;' \
+		-e 'print "$sudoers\n";' \
+		"$SUDOERS" >$SUDOERS_TEMPFILE
+
+	    # Check if sudoers file is ok with visudo and write to /etc/sudoers if
+	    # it is ok, else display a message to the user.
+	    if visudo -c -f $SUDOERS_TEMPFILE >/dev/null 2>&1; then
+		cat $SUDOERS_TEMPFILE >/etc/sudoers
+	    else
+		# TODO: Use debconf for this message.
+		echo "Couldn't edit /etc/sudoers, must be manually edited."
+		echo "Please edit /etc/sudoers using 'visudo' and add the following"
+		echo "entries:"
+		echo "$XBMC_ENTRIES"
+	    fi
+	fi
+	rm $SUDOERS_TEMPFILE
 
 	POLKIT_ACTIONS="org.freedesktop.hal.dockstation.undock
 		org.freedesktop.hal.wol.enabled
@@ -45,7 +75,10 @@ then
 		org.freedesktop.hal.power-management.cpufreq
 		org.freedesktop.hal.power-management.lcd-panel
 		org.freedesktop.hal.power-management.light-sensor
-		org.freedesktop.hal.power-management.keyboard-backlight"
+		org.freedesktop.hal.power-management.keyboard-backlight
+		org.freedesktop.devicekit.power.suspend
+		org.freedesktop.devicekit.power.Hibernate
+		org.freedesktop.consolekit.system.stop"
 
 	# Grant the 'xbmc' user each action from the list if not done already
 	for ACTION in $POLKIT_ACTIONS; do
