backport packaging changes to Camelot * move the debian folder * change the makefile to allow arch indep installs * add ppabuilder script * add XBMCLive changes * add xbmc-send man page
git-svn-id: https://xbmc.svn.sourceforge.net/svnroot/xbmc/branches/9.11_Camelot@25312 568bbfeb-2a22-0410-94d2-cc84cf5bfa90

diff --git a/tools/Linux/packaging/debian/xbmc-live.postrm b/tools/Linux/packaging/debian/xbmc-live.postrm
--- a/tools/Linux/packaging/debian/xbmc-live.postrm
+++ b/tools/Linux/packaging/debian/xbmc-live.postrm
@@ -1,9 +1,28 @@
 #!/bin/sh
+# postrm script for xbmc-live
+#
+# see: dh_installdeb(1)
 
 set -e
-if [ "$1" = "purge" ]                                                    
-then                            
-	sed -i -e "/XBMC/d" /etc/sudoers
+if [ "$1" = "purge" ]; then
+	SUDOERS_TEMPFILE=$(mktemp -q)
+
+	# Add xbmc to the sudoers file (if not already done)
+	if ! grep -i -q XBMC-specific /etc/sudoers ; then 
+		cat /etc/sudoers > $SUDOERS_TEMPFILE
+
+		sed -i -e "/XBMC/d" $SUDOERS_TEMPFILE
+
+		# Check if sudoers file is ok with visudo and write to /etc/sudoers if
+		# it is ok, else display a message to the user.
+		if visudo -c -f $SUDOERS_TEMPFILE >/dev/null 2>&1; then
+			cat $SUDOERS_TEMPFILE > /etc/sudoers
+		else
+			# TODO: Use debconf for this message.
+			echo "Couldn't edit /etc/sudoers, must be manually edited."
+			echo "Please edit /etc/sudoers using 'visudo' and remove the lines with 'XBMC'"
+		fi
+	fi
 
 	POLKIT_ACTIONS="org.freedesktop.hal.dockstation.undock
 		org.freedesktop.hal.wol.enabled
@@ -42,7 +61,10 @@ then
 		org.freedesktop.hal.power-management.cpufreq
 		org.freedesktop.hal.power-management.lcd-panel
 		org.freedesktop.hal.power-management.light-sensor
-		org.freedesktop.hal.power-management.keyboard-backlight"
+		org.freedesktop.hal.power-management.keyboard-backlight
+		org.freedesktop.devicekit.power.suspend
+		org.freedesktop.devicekit.power.Hibernate
+		org.freedesktop.consolekit.system.stop"
 
 	# Grant the 'xbmc' user each action from the list if not done already
 	for ACTION in $POLKIT_ACTIONS; do
@@ -71,6 +93,11 @@ then
 fi
 
 update-rc.d -f xbmc-live remove >/dev/null
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
 
 exit 0
 
