merged: changes from trunk. revs: r25025-25243
git-svn-id: https://xbmc.svn.sourceforge.net/svnroot/xbmc/branches/pvr-testing/XBMC@25244 568bbfeb-2a22-0410-94d2-cc84cf5bfa90

diff --git a/tools/Linux/packaging/debian/xbmc-live.postinst b/tools/Linux/packaging/debian/xbmc-live.postinst
--- a/tools/Linux/packaging/debian/xbmc-live.postinst
+++ b/tools/Linux/packaging/debian/xbmc-live.postinst
@@ -1,15 +1,25 @@
 #!/bin/sh
+# postinst script for xbmc-live
+#
+# see: dh_installdeb(1)
 
 set -e
 
 case "$1" in
     configure)
+	# TODO: What's the purpose of this line? As I see it, if 'xbmc' can't
+	# get a console session going, we're in trouble anyway. ceros
 	sed -i.bak-xbmc-live s/allowed_users=console/allowed_users=anybody/ /etc/X11/Xwrapper.config
 
 	# Add the 'xbmc' user if the primary one is missing
 	xbmcUser=$(getent passwd 1000 | sed -e 's/\:.*//')
 	if [ ! -n "$xbmcUser" ]; then
-		adduser --gecos "XBMC Live User" xbmc
+		clearTextPWD=xbmc
+		encryptedPWD=$(echo $clearTextPWD | mkpasswd -s)
+
+		adduser --disabled-password --gecos "XBMC Live User" xbmc
+		usermod -p $encryptedPWD xbmc
+
 		xbmcUser=xbmc
 	fi
 
@@ -45,17 +55,40 @@ case "$1" in
 		fi
 	done
 
+
+	SUDOERSBLOCK_TEMPFILE=$(mktemp -q)
+
+	cat > $SUDOERSBLOCK_TEMPFILE <<ENDOFBLOCK
+### XBMC-specific configuration ###
+# XBMC
+Cmnd_Alias SHUTDOWN_CMDS = /sbin/shutdown, /sbin/reboot, /sbin/halt # XBMC
+Cmnd_Alias MOUNT_CMDS = /bin/mount, /bin/umount # XBMC
+$xbmcUser ALL=(ALL) ALL # XBMC
+$xbmcUser ALL=NOPASSWD: SHUTDOWN_CMDS, MOUNT_CMDS # XBMC
+ENDOFBLOCK
+
+	SUDOERS_TEMPFILE=$(mktemp -q)
+
 	# Add xbmc to the sudoers file (if not already done)
-	if [ ! $(grep -i XBMC-specific /etc/sudoers) ]; then
-		echo "" >> /etc/sudoers
-		echo "# XBMC" >> /etc/sudoers
-		echo "# XBMC-specific configuration" >> /etc/sudoers
-		echo "# XBMC" >> /etc/sudoers
-		echo "Cmnd_Alias SHUTDOWN_CMDS = /sbin/shutdown, /sbin/reboot, /sbin/halt # XBMC"  >> /etc/sudoers
-		echo "Cmnd_Alias MOUNT_CMDS = /bin/mount, /bin/umount # XBMC" >> /etc/sudoers
-		echo "$xbmcUser ALL=(ALL) ALL" >> /etc/sudoers
-		echo "$xbmcUser ALL=NOPASSWD: SHUTDOWN_CMDS, MOUNT_CMDS # XBMC" >> /etc/sudoers
+	if ! grep -i -q XBMC-specific /etc/sudoers ; then 
+		cat /etc/sudoers $SUDOERSBLOCK_TEMPFILE > $SUDOERS_TEMPFILE
+
+		# Check if sudoers file is ok with visudo and write to /etc/sudoers if
+		# it is ok, else display a message to the user.
+		if visudo -c -f $SUDOERS_TEMPFILE >/dev/null 2>&1; then
+			cp $SUDOERS_TEMPFILE /etc/sudoers
+		else
+			# TODO: Use debconf for this message.
+			echo "Couldn't edit /etc/sudoers, must be manually edited."
+			echo "Please edit /etc/sudoers using 'visudo' and add the following"
+			echo "entries:"
+			cat $SUDOERSBLOCK_TEMPFILE
+		fi
 	fi
+
+	rm $SUDOERS_TEMPFILE
+	rm $SUDOERSBLOCK_TEMPFILE
+
 
 	# Our set of PolicyKit actions
 
@@ -99,7 +132,10 @@ case "$1" in
 		org.freedesktop.hal.power-management.cpufreq
 		org.freedesktop.hal.power-management.lcd-panel
 		org.freedesktop.hal.power-management.light-sensor
-		org.freedesktop.hal.power-management.keyboard-backlight"
+		org.freedesktop.hal.power-management.keyboard-backlight
+		org.freedesktop.devicekit.power.suspend
+		org.freedesktop.devicekit.power.Hibernate
+		org.freedesktop.consolekit.system.stop"
 
 	# Grant the 'xbmc' user each action from the list if not done already
 	for ACTION in $POLKIT_ACTIONS; do
@@ -144,4 +180,10 @@ else
 		fi
 	fi
 fi
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
 exit 0
