re-add libfaad wrapper to ffmpeg for now
git-svn-id: https://xbmc.svn.sourceforge.net/svnroot/xbmc/trunk@31799 568bbfeb-2a22-0410-94d2-cc84cf5bfa90

diff --git a/xbmc/cores/dvdplayer/Codecs/ffmpeg/configure b/xbmc/cores/dvdplayer/Codecs/ffmpeg/configure
--- a/xbmc/cores/dvdplayer/Codecs/ffmpeg/configure
+++ b/xbmc/cores/dvdplayer/Codecs/ffmpeg/configure
@@ -167,6 +167,8 @@ External library support:
                            and libraw1394 [no]
   --enable-libdirac        enable Dirac support via libdirac [no]
   --enable-libfaac         enable FAAC support via libfaac [no]
+  --enable-libfaad         enable FAAD support via libfaad [no]
+  --enable-libfaadbin      open libfaad.so.0 at runtime [no]
   --enable-libgsm          enable GSM support via libgsm [no]
   --enable-libmp3lame      enable MP3 encoding via libmp3lame [no]
   --enable-libnut          enable NUT (de)muxing via libnut,
@@ -869,6 +871,8 @@ CONFIG_LIST="
     libdc1394
     libdirac
     libfaac
+    libfaad
+    libfaadbin
     libgsm
     libmp3lame
     libnut
@@ -1300,6 +1304,8 @@ latm_parser_deps="libfaad"
 libdirac_decoder_deps="libdirac !libschroedinger"
 libdirac_encoder_deps="libdirac"
 libfaac_encoder_deps="libfaac"
+libfaad_decoder_deps="libfaad"
+libfaadbin_extralibs='$ldl'
 libfaad_latm_decoder_deps="libfaad"
 libfaadbin_decoder_extralibs='$ldl'
 libgsm_decoder_deps="libgsm"
@@ -2353,10 +2359,26 @@ fi
 
 disabled static && LIBNAME=""
 
+if enabled_any libfaad libfaadbin ; then
+    if check_header faad.h; then
+        check_cc <<EOF
+#include <faad.h>
+#ifndef FAAD2_VERSION
+ok faad1
+#endif
+int main(void) { return 0; }
+EOF
+        test $? = 0 && enable libfaad2
+    else
+        die "FAAD test failed."
+    fi
+fi
+
 die_license_disabled() {
     enabled $1 || { enabled $2 && die "$2 is $1 and --enable-$1 is not specified."; }
 }
 
+die_license_disabled gpl libfaad2
 die_license_disabled gpl libx264
 die_license_disabled gpl libxvid
 die_license_disabled gpl postproc
@@ -2646,6 +2668,7 @@ enabled libdirac   && add_cflags $(pkg-config --cflags dirac) &&
                       require  libdirac libdirac_decoder/dirac_parser.h dirac_decoder_init $(pkg-config --libs dirac) &&
                       require  libdirac libdirac_encoder/dirac_encoder.h dirac_encoder_init $(pkg-config --libs dirac)
 enabled libfaac    && require2 libfaac "stdint.h faac.h" faacEncGetVersion -lfaac
+enabled libfaad    && require2 libfaad faad.h faacDecOpen -lfaad
 enabled libgsm     && require  libgsm gsm/gsm.h gsm_create -lgsm
 enabled libmp3lame && require  libmp3lame lame/lame.h lame_init -lmp3lame
 enabled libnut     && require  libnut libnut.h nut_demuxer_init -lnut
@@ -2924,6 +2947,8 @@ echo "AVISynth enabled          ${avisynth-no}"
 echo "libdc1394 support         ${libdc1394-no}"
 echo "libdirac enabled          ${libdirac-no}"
 echo "libfaac enabled           ${libfaac-no}"
+echo "libfaad enabled           ${libfaad-no}"
+echo "libfaad dlopened          ${libfaadbin-no}"
 echo "libgsm enabled            ${libgsm-no}"
 echo "libmp3lame enabled        ${libmp3lame-no}"
 echo "libnut enabled            ${libnut-no}"
