Merge remote branch 'origin/trunk' into AudioEngine
git-svn-id: https://xbmc.svn.sourceforge.net/svnroot/xbmc/branches/AudioEngine@35713 568bbfeb-2a22-0410-94d2-cc84cf5bfa90

diff --git a/tools/Linux/xbmc.sh.in b/tools/Linux/xbmc.sh.in
--- a/tools/Linux/xbmc.sh.in
+++ b/tools/Linux/xbmc.sh.in
@@ -40,11 +40,14 @@ done
 
 single_stacktrace()
 {
-  find $1 -maxdepth $2 -name 'core*' \( -exec \
-      echo "=====>  Core file: {}" 2> /dev/null >> $FILE \; , -exec \
-      echo "        ========================================= " 2> /dev/null >> $FILE \; , -exec \
-      gdb "$LIBDIR/xbmc/xbmc.bin" --core={} --batch -ex "thread apply all bt" 2> /dev/null >> $FILE \; , -exec \
-      rm -f {} \; \)
+  # core filename is either "core.$PID" or "core"
+  find "$1" -maxdepth $2 -name 'core*' | while read core; do
+      LC_ALL=C gdb --core="$core" --batch 2> /dev/null | grep -q "^Core was generated by \`$LIBDIR/xbmc/xbmc.bin" || continue
+      echo "=====>  Core file: "$core" ($(stat -c%y "$core"))" >> $FILE
+      echo "        =========================================" >> $FILE
+      gdb "$LIBDIR/xbmc/xbmc.bin" --core="$core" --batch -ex "thread apply all bt" 2> /dev/null >> $FILE
+      rm -f "$core"
+  done
 }
 
 print_crash_report()
@@ -70,16 +73,20 @@ print_crash_report()
   echo "############## END SYSTEM INFO ##############" >> $FILE
   echo >> $FILE
   echo "############### STACK TRACE #################" >> $FILE
-  single_stacktrace $PWD 1
-  # Find in plugins directories
-  if [ $XBMC_HOME ]; then
-    BASEDIR=$XBMC_HOME
+  if which gdb >/dev/null 2>&1; then
+    single_stacktrace "$PWD" 1
+    # Find in plugins directories
+    if [ $XBMC_HOME ]; then
+      BASEDIR=$XBMC_HOME
+    else
+      BASEDIR="$LIBDIR/xbmc/"
+    fi
+    single_stacktrace "$BASEDIR" 5
+    # find in user xbmc dir
+    single_stacktrace $HOME/.xbmc/ 5
   else
-    BASEDIR="$LIBDIR/xbmc/"
+    echo "gdb not installed, can't get stack trace." >> $FILE
   fi
-  single_stacktrace $BASEDIR 5
-  # find in user xbmc dir
-  single_stacktrace $HOME/.xbmc/ 5
   echo "############# END STACK TRACE ###############" >> $FILE
   echo >> $FILE
   echo "################# LOG FILE ##################" >> $FILE
@@ -106,10 +113,12 @@ if [ $RET -ne 0 ]; then
   exit $RET
 fi
 
-# Output warning in case ulimit is unsupported by shell
-eval ulimit -c unlimited
-if [ ! $? = "0" ]; then
-  echo "xbmc: ulimit is unsupported by this shell" 1>&2
+if which gdb >/dev/null 2>&1; then
+  # Output warning in case ulimit is unsupported by shell
+  eval ulimit -c unlimited
+  if [ ! $? = "0" ]; then
+    echo "xbmc: ulimit is unsupported by this shell" 1>&2
+  fi
 fi
 
 LOOP=1
