[Dsplayer] updated to head revision of trunk Part 1
git-svn-id: https://xbmc.svn.sourceforge.net/svnroot/xbmc/branches/dsplayer@25865 568bbfeb-2a22-0410-94d2-cc84cf5bfa90

diff --git a/tools/XBMCLive/runXBMC b/tools/XBMCLive/runXBMC
--- a/tools/XBMCLive/runXBMC
+++ b/tools/XBMCLive/runXBMC
@@ -1,24 +1,35 @@
 #!/bin/bash
 
+if [ "$(pidof xbmc.bin)" ] ; then
+	exit
+fi
+
 if [ "$(pidof X)" ] ; then
-	/usr/share/xbmc/xbmc.bin  --standalone
+	/usr/bin/xbmc --standalone
 	exit
 fi
 
 while true
 do
 	if [ "$(whoami)" == "root" ] ; then
-		xbmcUser=$(getent passwd 1000 | sed -e 's/\:.*//')
-		if [ -z "$xbmcUser" ]; then
-			echo "User for XBMC not found, exiting..."
-			break
+		xbmcUser=xbmc
+
+		# Read configuration variable file if it is present
+		[ -r /etc/default/xbmc-live ] && . /etc/default/xbmc-live
+
+		if ! getent passwd $xbmcUser >/dev/null; then
+			xbmcUser=$(getent passwd 1000 | sed -e 's/\:.*//')
+			if [ -z "$xbmcUser" ]; then
+				echo "User for XBMC not found, exiting..."
+				break
+			fi
 		fi
 	else
 		xbmcUser=$(whoami)
 	fi
 
 	echo "#!/bin/bash" >  /home/$xbmcUser/.xsession
-	echo "/usr/share/xbmc/xbmc.bin  --standalone" >>  /home/$xbmcUser/.xsession
+	echo "/usr/bin/xbmc --standalone" >>  /home/$xbmcUser/.xsession
 
 	echo "case \"\$?\" in" >>  /home/$xbmcUser/.xsession
 	echo "    0 ) # Quit" >>  /home/$xbmcUser/.xsession
