merged: changes from trunk. revs: r24918:25023
git-svn-id: https://xbmc.svn.sourceforge.net/svnroot/xbmc/branches/pvr-testing/XBMC@25029 568bbfeb-2a22-0410-94d2-cc84cf5bfa90

diff --git a/tools/XBMCLive/runXBMC b/tools/XBMCLive/runXBMC
--- a/tools/XBMCLive/runXBMC
+++ b/tools/XBMCLive/runXBMC
@@ -8,10 +8,17 @@ fi
 while true
 do
 	if [ "$(whoami)" == "root" ] ; then
-		xbmcUser=$(getent passwd 1000 | sed -e 's/\:.*//')
-		if [ -z "$xbmcUser" ]; then
-			echo "User for XBMC not found, exiting..."
-			break
+		xbmcUser=xbmc
+
+		# Read configuration variable file if it is present
+		[ -r /etc/default/xbmc-live ] && . /etc/default/xbmc-live
+
+		if ! getent passwd $xbmcUser >/dev/null; then
+			xbmcUser=$(getent passwd 1000 | sed -e 's/\:.*//')
+			if [ -z "$xbmcUser" ]; then
+				echo "User for XBMC not found, exiting..."
+				break
+			fi
 		fi
 	else
 		xbmcUser=$(whoami)
