modified: allow xbmc to use external libdts library
git-svn-id: https://xbmc.svn.sourceforge.net/svnroot/xbmc/branches/external-libraries-support@17435 568bbfeb-2a22-0410-94d2-cc84cf5bfa90

diff --git a/XBMC/configure b/XBMC/configure
--- a/XBMC/configure
+++ b/XBMC/configure
@@ -699,6 +699,7 @@ USE_EXTERNAL_LIBRARIES
 USE_EXTERNAL_FFMPEG
 USE_EXTERNAL_LIBMAD
 USE_EXTERNAL_LIBA52
+USE_EXTERNAL_LIBDTS
 LTLIBOBJS'
 ac_subst_files=''
       ac_precious_vars='build_alias
@@ -1311,6 +1312,9 @@ Optional Features:
   --enable-external-liba52
                           enable use of external liba52 library (default is
                           no)
+  --enable-external-libdts
+                          enable use of external libdts library (default is
+                          no)
 
 Some influential environment variables:
   CXX         C++ compiler command
@@ -1919,6 +1923,8 @@ external_libmad_enabled="== Use of external libmad enabled. =="
 external_libmad_disabled="== Use of external libmad disabled. =="
 external_liba52_enabled="== Use of external liba52 enabled. =="
 external_liba52_disabled="== Use of external liba52 disabled. =="
+external_libdts_enabled="== Use of external libdts enabled. =="
+external_libdts_disabled="== Use of external libdts disabled. =="
 
 case $host in
     i*86*-linux-gnu*)
@@ -2099,6 +2105,14 @@ if test "${enable_external_liba52+set}" = set; then
   enableval=$enable_external_liba52; use_external_liba52=$enableval
 else
   use_external_liba52=no
+fi
+
+
+# Check whether --enable-external-libdts was given.
+if test "${enable_external_libdts+set}" = set; then
+  enableval=$enable_external_libdts; use_external_libdts=$enableval
+else
+  use_external_libdts=no
 fi
 
 
@@ -8957,6 +8971,93 @@ else
 echo "$as_me: $external_liba52_disabled" >&6;}
   USE_EXTERNAL_LIBA52=0
 fi
+
+# External libdts
+if test "$use_external_libraries" = "yes" || test "$use_external_libdts" = "yes"; then
+
+{ echo "$as_me:$LINENO: checking for main in -ldts" >&5
+echo $ECHO_N "checking for main in -ldts... $ECHO_C" >&6; }
+if test "${ac_cv_lib_dts_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-ldts  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+return main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_dts_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_dts_main=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_dts_main" >&5
+echo "${ECHO_T}$ac_cv_lib_dts_main" >&6; }
+if test $ac_cv_lib_dts_main = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBDTS 1
+_ACEOF
+
+  LIBS="-ldts $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: $missing_library" >&5
+echo "$as_me: error: $missing_library" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+  { echo "$as_me:$LINENO: $external_libdts_enabled" >&5
+echo "$as_me: $external_libdts_enabled" >&6;}
+  USE_EXTERNAL_LIBDTS=1
+
+cat >>confdefs.h <<\_ACEOF
+#define USE_EXTERNAL_LIBDTS 1
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: $external_libdts_disabled" >&5
+echo "$as_me: $external_libdts_disabled" >&6;}
+  USE_EXTERNAL_LIBDTS=0
+fi
+
 
 # Python
 if test "$host_cpu" = "powerpc" ; then
@@ -15893,7 +15994,13 @@ else
   else
     final_message="$final_message\n  External liba52:\tNo"
   fi
+  if test "$use_external_libdts" = "yes"; then
+    final_message="$final_message\n  External libdts:\tYes"
+  else
+    final_message="$final_message\n  External libdts:\tNo"
+  fi
 fi
+
 
 
 
@@ -16731,10 +16838,11 @@ USE_EXTERNAL_LIBRARIES!$USE_EXTERNAL_LIBRARIES$ac_delim
 USE_EXTERNAL_FFMPEG!$USE_EXTERNAL_FFMPEG$ac_delim
 USE_EXTERNAL_LIBMAD!$USE_EXTERNAL_LIBMAD$ac_delim
 USE_EXTERNAL_LIBA52!$USE_EXTERNAL_LIBA52$ac_delim
+USE_EXTERNAL_LIBDTS!$USE_EXTERNAL_LIBDTS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 84; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 85; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -17390,7 +17498,7 @@ echo "$as_me: Skipping configuration of submodule xbmc/cores/dvdplayer/Codecs/ff
 fi
 
 
-if [ 0 != "1" ]; then
+if [ $USE_EXTERNAL_LIBDTS != "1" ]; then
     if [ -d xbmc/cores/dvdplayer/Codecs/libdts ]; then
         pushd xbmc/cores/dvdplayer/Codecs/libdts
 
