added: configure check for libuuid++ extendet to find renamed debian one (libossp-uuid++) added: ifdef's for libossp-uuid++ in CUtil fixed: compile fixes under WIN32, also tested the CreateGUID function under Win (OK)
git-svn-id: https://xbmc.svn.sourceforge.net/svnroot/xbmc/branches/unified-pvr@20597 568bbfeb-2a22-0410-94d2-cc84cf5bfa90

diff --git a/XBMC/configure b/XBMC/configure
--- a/XBMC/configure
+++ b/XBMC/configure
@@ -6073,6 +6073,70 @@ echo "$as_me: error: $missing_library" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
+{ echo "$as_me:$LINENO: checking for main in -lossp-uuid++" >&5
+echo $ECHO_N "checking for main in -lossp-uuid++... $ECHO_C" >&6; }
+if test "${ac_cv_lib_uuidossp_uuidpp_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lossp-uuid++  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+return main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_ossp_uuidpp_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_ossp_uuidpp_main=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_ossp_uuidpp_main" >&5
+echo "${ECHO_T}$ac_cv_lib_ossp_uuidpp_main" >&6; }
+if test $ac_cv_lib_ossp_uuidpp_main = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBOSSP_UUID__ 1
+_ACEOF
+
+  LIBS="-lossp-uuid++ $LIBS"
+
+else
+
 { echo "$as_me:$LINENO: checking for main in -luuid++" >&5
 echo $ECHO_N "checking for main in -luuid++... $ECHO_C" >&6; }
 if test "${ac_cv_lib_uuidpp_main+set}" = set; then
@@ -6121,7 +6185,6 @@ sed 's/^/| /' conftest.$ac_ext >&5
 
 	ac_cv_lib_uuidpp_main=no
 fi
-
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
@@ -6136,8 +6199,9 @@ _ACEOF
   LIBS="-luuid++ $LIBS"
 
 else
-  { echo "$as_me:$LINENO: ERROR: Could not find libuuid++ - falling back to time based internal generation" >&5
-  echo "ERROR: Could not find libuuid++ - falling back to time based internal generation" >&6;}
+  { echo "$as_me:$LINENO: WARNING: Could not find libossp-uuid++ or libuuid++ - falling back to time based internal generation" >&5
+  echo "WARNING: Could not find libossp-uuid++ or libuuid++ - falling back to time based internal generation" >&6;}
+fi
 fi
 
 # platform dependent libraries
