Merge commit 'svn/linuxport@18805' into xbmc-vdpau WARNING: users must delete their videodb after this update due to changes in linuxport          ~/.xbmc/userdata/Database/MyVideos34.db
Conflicts:

	config.h.in
	configure
	guilib/GraphicContext.cpp
	xbmc/VideoDatabase.cpp
	xbmc/cores/dvdplayer/DVDFileInfo.cpp
	xbmc/cores/dvdplayer/DVDPlayer.cpp


git-svn-id: https://xbmc.svn.sourceforge.net/svnroot/xbmc/branches/xbmc-vdpau@18811 568bbfeb-2a22-0410-94d2-cc84cf5bfa90

diff --git a/XBMC/configure b/XBMC/configure
--- a/XBMC/configure
+++ b/XBMC/configure
@@ -5990,6 +5990,75 @@ fi
 
 fi
 
+
+{ echo "$as_me:$LINENO: checking for main in -lcdio" >&5
+echo $ECHO_N "checking for main in -lcdio... $ECHO_C" >&6; }
+if test "${ac_cv_lib_cdio_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lcdio  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+return main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_cdio_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_cdio_main=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_cdio_main" >&5
+echo "${ECHO_T}$ac_cv_lib_cdio_main" >&6; }
+if test $ac_cv_lib_cdio_main = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBCDIO 1
+_ACEOF
+
+  LIBS="-lcdio $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: $missing_library" >&5
+echo "$as_me: error: $missing_library" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 # platform dependent libraries
 if test "$host_vendor" = "apple" ; then
 
@@ -12002,7 +12071,6 @@ cat >>conftest.$ac_ext <<_ACEOF
 # endif
 #endif
 
-#include <limits.h>
 #include <stdlib.h>
 
 #ifdef HAVE_UNISTD_H
@@ -12151,15 +12219,12 @@ main ()
      isn't worth using anyway.  */
   alarm (60);
 
-  for (;;)
-    {
-      t = (time_t_max << 1) + 1;
-      if (t <= time_t_max)
-	break;
-      time_t_max = t;
-    }
-  time_t_min = - ((time_t) ~ (time_t) 0 == (time_t) -1) - time_t_max;
-
+  for (time_t_max = 1; 0 < time_t_max; time_t_max *= 2)
+    continue;
+  time_t_max--;
+  if ((time_t) -1 < 0)
+    for (time_t_min = -1; (time_t) (time_t_min * 2) < 0; time_t_min *= 2)
+      continue;
   delta = time_t_max / 997; /* a suitable prime number */
   for (i = 0; i < N_STRINGS; i++)
     {
@@ -12174,12 +12239,10 @@ main ()
 	     && mktime_test ((time_t) (60 * 60 * 24))))
 	return 1;
 
-      for (j = 1; ; j <<= 1)
+      for (j = 1; 0 < j; j *= 2)
 	if (! bigtime_test (j))
 	  return 1;
-	else if (INT_MAX / 2 < j)
-	  break;
-      if (! bigtime_test (INT_MAX))
+      if (! bigtime_test (j - 1))
 	return 1;
     }
   return ! (irix_6_4_bug () && spring_forward_gap () && year_2050_test ());
@@ -14465,7 +14528,7 @@ fi
 
 
 
-ac_config_files="$ac_config_files Makefile Makefile.include guilib/common/Makefile xbmc/DllPaths_generated.h xbmc/cores/dvdplayer/Codecs/Makefile xbmc/cores/AudioRenderers/Makefile xbmc/cores/paplayer/Makefile xbmc/cores/paplayer/AACCodec/Makefile xbmc/cores/paplayer/MACDll/Makefile xbmc/cores/paplayer/timidity/Makefile xbmc/cores/paplayer/AC3Codec/Makefile xbmc/cores/paplayer/ADPCMCodec/Makefile xbmc/cores/paplayer/ModuleCodec/vc6/dumb/Makefile xbmc/cores/paplayer/GYMCodec/Makefile xbmc/cores/paplayer/MP3Codec/Makefile xbmc/cores/paplayer/MPCCodec/xbmc/Makefile xbmc/cores/paplayer/NSFCodec/Makefile xbmc/cores/paplayer/SIDCodec/Makefile xbmc/cores/paplayer/vgmstream/Makefile xbmc/cores/paplayer/SPCCodec/SNES/SNESAPU/Makefile xbmc/cores/paplayer/vorbisfile/Makefile xbmc/cores/paplayer/WavPackCodec/Makefile xbmc/cores/paplayer/YMCodec/StSoundLibrary/Makefile xbmc/lib/cximage-6.0/Makefile xbmc/lib/libass/xbmc/Makefile xbmc/lib/libXBMS/Makefile xbmc/lib/libRTV/Makefile xbmc/lib/libexif/Makefile xbmc/lib/libXDAAP/Makefile xbmc/lib/libhdhomerun/Makefile xbmc/lib/libGoAhead/Makefile xbmc/lib/libshout/Makefile xbmc/lib/libid3tag/Makefile xbmc/lib/libPython/linux/Makefile xbmc/lib/libUPnP/Makefile xbmc/linux/Makefile xbmc/screensavers/Makefile tools/Linux/xbmc.sh tools/XBMCTex/Makefile"
+ac_config_files="$ac_config_files Makefile Makefile.include guilib/common/Makefile xbmc/DllPaths_generated.h xbmc/cores/dvdplayer/Codecs/Makefile xbmc/cores/AudioRenderers/Makefile xbmc/cores/paplayer/Makefile xbmc/cores/paplayer/AACCodec/Makefile xbmc/cores/paplayer/MACDll/Makefile xbmc/cores/paplayer/timidity/Makefile xbmc/cores/paplayer/AC3Codec/Makefile xbmc/cores/paplayer/ADPCMCodec/Makefile xbmc/cores/paplayer/ModuleCodec/vc6/dumb/Makefile xbmc/cores/paplayer/GYMCodec/Makefile xbmc/cores/paplayer/MP3Codec/Makefile xbmc/cores/paplayer/MPCCodec/xbmc/Makefile xbmc/cores/paplayer/NSFCodec/Makefile xbmc/cores/paplayer/SIDCodec/Makefile xbmc/cores/paplayer/vgmstream/Makefile xbmc/cores/paplayer/SPCCodec/SNES/SNESAPU/Makefile xbmc/cores/paplayer/vorbisfile/Makefile xbmc/cores/paplayer/WavPackCodec/Makefile xbmc/cores/paplayer/YMCodec/StSoundLibrary/Makefile xbmc/lib/cximage-6.0/Makefile xbmc/lib/libass/xbmc/Makefile xbmc/lib/libXBMS/Makefile xbmc/lib/libRTV/Makefile xbmc/lib/libexif/Makefile xbmc/lib/libXDAAP/Makefile xbmc/lib/libhdhomerun/Makefile xbmc/lib/libGoAhead/Makefile xbmc/lib/libshout/Makefile xbmc/lib/libid3tag/Makefile xbmc/lib/libPython/linux/Makefile xbmc/lib/libUPnP/Makefile xbmc/linux/Makefile xbmc/screensavers/Makefile xbmc/screensavers/rsxs-0.9/xbmc/Makefile xbmc/visualizations/XBMCProjectM/Makefile xbmc/visualizations/Goom/Makefile xbmc/visualizations/OpenGLSpectrum/Makefile xbmc/visualizations/WaveForm/Makefile xbmc/visualizations/iTunes/Makefile tools/Linux/xbmc.sh tools/XBMCTex/Makefile"
 
 
 
@@ -14523,9 +14586,6 @@ echo "$as_me: error: Submodule xbmc/cores/dvdplayer/Codecs/libDVDCSS doesn't exi
    { (exit 1); exit 1; }; }
     fi;
 fi
-
-
-
 
 
 
@@ -15158,6 +15218,12 @@ do
     "xbmc/lib/libUPnP/Makefile") CONFIG_FILES="$CONFIG_FILES xbmc/lib/libUPnP/Makefile" ;;
     "xbmc/linux/Makefile") CONFIG_FILES="$CONFIG_FILES xbmc/linux/Makefile" ;;
     "xbmc/screensavers/Makefile") CONFIG_FILES="$CONFIG_FILES xbmc/screensavers/Makefile" ;;
+    "xbmc/screensavers/rsxs-0.9/xbmc/Makefile") CONFIG_FILES="$CONFIG_FILES xbmc/screensavers/rsxs-0.9/xbmc/Makefile" ;;
+    "xbmc/visualizations/XBMCProjectM/Makefile") CONFIG_FILES="$CONFIG_FILES xbmc/visualizations/XBMCProjectM/Makefile" ;;
+    "xbmc/visualizations/Goom/Makefile") CONFIG_FILES="$CONFIG_FILES xbmc/visualizations/Goom/Makefile" ;;
+    "xbmc/visualizations/OpenGLSpectrum/Makefile") CONFIG_FILES="$CONFIG_FILES xbmc/visualizations/OpenGLSpectrum/Makefile" ;;
+    "xbmc/visualizations/WaveForm/Makefile") CONFIG_FILES="$CONFIG_FILES xbmc/visualizations/WaveForm/Makefile" ;;
+    "xbmc/visualizations/iTunes/Makefile") CONFIG_FILES="$CONFIG_FILES xbmc/visualizations/iTunes/Makefile" ;;
     "tools/Linux/xbmc.sh") CONFIG_FILES="$CONFIG_FILES tools/Linux/xbmc.sh" ;;
     "tools/XBMCTex/Makefile") CONFIG_FILES="$CONFIG_FILES tools/XBMCTex/Makefile" ;;
 
@@ -15714,7 +15780,8 @@ if [ -d xbmc/lib/libPython/Python ]; then
       --without-cxx \
       --enable-shared \
       --without-pymalloc \
-      OPT="-Wno-deprecated-declarations" \
+      LDFLAGS="-L/opt/local/lib" \
+      OPT="-Wno-deprecated-declarations -I/opt/local/include" \
       MACOSX_DEPLOYMENT_TARGET=10.4 &&
     sed -i bak -e "s/define HAVE_GETC_UNLOCKED 1/undef HAVE_GETC_UNLOCKED/" pyconfig.h &&
     sed -i bak -e "s/define HAVE_FSEEKO 1/undef HAVE_FSEEKO/" pyconfig.h &&
@@ -16220,7 +16287,11 @@ fi;
 if [ -d xbmc/visualizations/XBMCProjectM/libprojectM ]; then
   pushd xbmc/visualizations/XBMCProjectM/libprojectM
 
-  rm -f CMakeCache.txt && CC="" CXX=""  cmake -D CMAKE_BUILD_TYPE:STRING=RelWithDebInfo -D USE_FTGL:BOOL=OFF .
+  if test "$host_vendor" = "apple" ; then
+    rm -f CMakeCache.txt && CC="" CXX=""  cmake -D CMAKE_C_FLAGS:STRING="-fno-common" -D CMAKE_CXX_FLAGS:STRING="-fno-common" -D CMAKE_BUILD_TYPE:STRING=RelWithDebInfo -D USE_FTGL:BOOL=OFF .
+  else
+    rm -f CMakeCache.txt && CC="" CXX=""  cmake -D CMAKE_BUILD_TYPE:STRING=RelWithDebInfo -D USE_FTGL:BOOL=OFF .
+  fi
 
   if [ $? -ne 0 ]; then
     popd
@@ -16278,6 +16349,9 @@ if [ -d xbmc/screensavers/rsxs-0.9/ ]; then
     ./configure \
       CFLAGS="-fPIC -isysroot /Developer/SDKs/MacOSX10.4u.sdk -mmacosx-version-min=10.4" \
       CXXFLAGS="-fPIC -isysroot /Developer/SDKs/MacOSX10.4u.sdk -mmacosx-version-min=10.4" \
+      LDFLAGS="-L/opt/local/lib" \
+      LIBS="-lz" \
+      --x-includes=/usr/X11/include --x-libraries=/usr/X11/lib \
       --without-xscreensaver \
       --disable-sound \
       --disable-cyclone \
@@ -16287,7 +16361,7 @@ if [ -d xbmc/screensavers/rsxs-0.9/ ]; then
       --disable-helios \
       --disable-hyperspace \
       --disable-lattice \
-       --disable-skyrocket
+      --disable-skyrocket
   else
     ./configure \
       CFLAGS="-fPIC" \
@@ -16315,31 +16389,6 @@ echo "$as_me: error: Submodule xbmc/screensavers/rsxs-0.9/ failed to configure" 
 else
   { { echo "$as_me:$LINENO: error: Submodule xbmc/screensavers/rsxs-0.9/ doesn't exist" >&5
 echo "$as_me: error: Submodule xbmc/screensavers/rsxs-0.9/ doesn't exist" >&2;}
-   { (exit 1); exit 1; }; }
-fi;
-
-
-if [ -d xbmc/lib/libcdio/libcdio ]; then
-  pushd xbmc/lib/libcdio/libcdio
-
-  if test "$host_vendor" = "apple" ; then
-    CFLAGS="-isysroot /Developer/SDKs/MacOSX10.4u.sdk -mmacosx-version-min=10.4" \
-    ./configure MACOSX_DEPLOYMENT_TARGET=10.4
-  else
-    ./configure
-  fi
-
-  if [ $? -ne 0 ]; then
-    popd
-    { { echo "$as_me:$LINENO: error: Submodule xbmc/lib/libcdio/libcdio failed to configure" >&5
-echo "$as_me: error: Submodule xbmc/lib/libcdio/libcdio failed to configure" >&2;}
-   { (exit 1); exit 1; }; }
-  else
-    popd
-  fi;
-else
-  { { echo "$as_me:$LINENO: error: Submodule xbmc/lib/libcdio/libcdio doesn't exist" >&5
-echo "$as_me: error: Submodule xbmc/lib/libcdio/libcdio doesn't exist" >&2;}
    { (exit 1); exit 1; }; }
 fi;
 
