modified: allow xbmc to use external liba52 libraries.
git-svn-id: https://xbmc.svn.sourceforge.net/svnroot/xbmc/branches/external-libraries-support@17434 568bbfeb-2a22-0410-94d2-cc84cf5bfa90

diff --git a/XBMC/configure b/XBMC/configure
--- a/XBMC/configure
+++ b/XBMC/configure
@@ -698,6 +698,7 @@ BUILD_DVDCSS
 USE_EXTERNAL_LIBRARIES
 USE_EXTERNAL_FFMPEG
 USE_EXTERNAL_LIBMAD
+USE_EXTERNAL_LIBA52
 LTLIBOBJS'
 ac_subst_files=''
       ac_precious_vars='build_alias
@@ -1307,6 +1308,9 @@ Optional Features:
   --enable-external-libmad
                           enable use of external libmad library (default is
                           no)
+  --enable-external-liba52
+                          enable use of external liba52 library (default is
+                          no)
 
 Some influential environment variables:
   CXX         C++ compiler command
@@ -1913,6 +1917,8 @@ external_ffmpeg_enabled="== Use of external ffmpeg enabled. =="
 external_ffmpeg_disabled="== Use of external ffmpeg disabled. =="
 external_libmad_enabled="== Use of external libmad enabled. =="
 external_libmad_disabled="== Use of external libmad disabled. =="
+external_liba52_enabled="== Use of external liba52 enabled. =="
+external_liba52_disabled="== Use of external liba52 disabled. =="
 
 case $host in
     i*86*-linux-gnu*)
@@ -2085,6 +2091,14 @@ if test "${enable_external_libmad+set}" = set; then
   enableval=$enable_external_libmad; use_external_libmad=$enableval
 else
   use_external_libmad=no
+fi
+
+
+# Check whether --enable-external-liba52 was given.
+if test "${enable_external_liba52+set}" = set; then
+  enableval=$enable_external_liba52; use_external_liba52=$enableval
+else
+  use_external_liba52=no
 fi
 
 
@@ -8856,6 +8870,92 @@ else
   { echo "$as_me:$LINENO: $external_libmad_disabled" >&5
 echo "$as_me: $external_libmad_disabled" >&6;}
   USE_EXTERNAL_LIBMAD=0
+fi
+
+# External liba52
+if test "$use_external_libraries" = "yes" || test "$use_external_liba52" = "yes"; then
+
+{ echo "$as_me:$LINENO: checking for main in -la52" >&5
+echo $ECHO_N "checking for main in -la52... $ECHO_C" >&6; }
+if test "${ac_cv_lib_a52_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-la52  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+return main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_a52_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_a52_main=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_a52_main" >&5
+echo "${ECHO_T}$ac_cv_lib_a52_main" >&6; }
+if test $ac_cv_lib_a52_main = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBA52 1
+_ACEOF
+
+  LIBS="-la52 $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: $missing_library" >&5
+echo "$as_me: error: $missing_library" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+  { echo "$as_me:$LINENO: $external_liba52_enabled" >&5
+echo "$as_me: $external_liba52_enabled" >&6;}
+  USE_EXTERNAL_LIBA52=1
+
+cat >>confdefs.h <<\_ACEOF
+#define USE_EXTERNAL_LIBA52 1
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: $external_liba52_disabled" >&5
+echo "$as_me: $external_liba52_disabled" >&6;}
+  USE_EXTERNAL_LIBA52=0
 fi
 
 # Python
@@ -15788,7 +15888,13 @@ else
   else
     final_message="$final_message\n  External libmad:\tNo"
   fi
+  if test "$use_external_liba52" = "yes"; then
+    final_message="$final_message\n  External liba52:\tYes"
+  else
+    final_message="$final_message\n  External liba52:\tNo"
+  fi
 fi
+
 
 
 
@@ -16624,10 +16730,11 @@ BUILD_DVDCSS!$BUILD_DVDCSS$ac_delim
 USE_EXTERNAL_LIBRARIES!$USE_EXTERNAL_LIBRARIES$ac_delim
 USE_EXTERNAL_FFMPEG!$USE_EXTERNAL_FFMPEG$ac_delim
 USE_EXTERNAL_LIBMAD!$USE_EXTERNAL_LIBMAD$ac_delim
+USE_EXTERNAL_LIBA52!$USE_EXTERNAL_LIBA52$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 83; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 84; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -17431,7 +17538,7 @@ echo "$as_me: Skipping configuration of submodule xbmc/cores/dvdplayer/Codecs/li
 fi
 
 
-if [ 0 != "1" ]; then
+if [ $USE_EXTERNAL_LIBA52 != "1" ]; then
     if [ -d xbmc/cores/dvdplayer/Codecs/liba52 ]; then
         pushd xbmc/cores/dvdplayer/Codecs/liba52
 
