modified: allowed xbmc to use external libmad
git-svn-id: https://xbmc.svn.sourceforge.net/svnroot/xbmc/branches/external-libraries-support@17281 568bbfeb-2a22-0410-94d2-cc84cf5bfa90

diff --git a/XBMC/configure b/XBMC/configure
--- a/XBMC/configure
+++ b/XBMC/configure
@@ -8470,6 +8470,76 @@ fi
 done
 
 
+
+{ echo "$as_me:$LINENO: checking for main in -lmad" >&5
+echo $ECHO_N "checking for main in -lmad... $ECHO_C" >&6; }
+if test "${ac_cv_lib_mad_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lmad  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+return main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_mad_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_mad_main=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_mad_main" >&5
+echo "${ECHO_T}$ac_cv_lib_mad_main" >&6; }
+if test $ac_cv_lib_mad_main = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBMAD 1
+_ACEOF
+
+  LIBS="-lmad $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: $missing_library" >&5
+echo "$as_me: error: $missing_library" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
   { echo "$as_me:$LINENO: $external_libraries_enabled" >&5
 echo "$as_me: $external_libraries_enabled" >&6;}
   USE_EXTERNAL_LIBRARIES=1
@@ -8478,6 +8548,7 @@ cat >>confdefs.h <<\_ACEOF
 #define USE_EXTERNAL_LIBRARIES 1
 _ACEOF
 
+  INCLUDES="$INCLUDES -I\$(abs_top_srcdir)"
 else
   { echo "$as_me:$LINENO: $external_libraries_disabled" >&5
 echo "$as_me: $external_libraries_disabled" >&6;}
@@ -17136,7 +17207,7 @@ echo "$as_me: Skipping configuration of submodule xbmc/cores/dvdplayer/Codecs/li
 fi
 
 
-if [ 0 != "1" ]; then
+if [ $USE_EXTERNAL_LIBRARIES != "1" ]; then
     if [ -d xbmc/cores/dvdplayer/Codecs/libmad ]; then
         pushd xbmc/cores/dvdplayer/Codecs/libmad
 
