changed: don't link with vdpau statically changed: only check for the precense of vdpau header at compile time
git-svn-id: https://xbmc.svn.sourceforge.net/svnroot/xbmc/branches/linuxport@19252 568bbfeb-2a22-0410-94d2-cc84cf5bfa90

diff --git a/XBMC/configure b/XBMC/configure
--- a/XBMC/configure
+++ b/XBMC/configure
@@ -7699,38 +7699,35 @@ if test "$host_vendor" = "apple" ; then
 echo "$as_me: $vdpau_disabled" >&6;}
 else
   if test "$use_vdpau" = "yes"; then
-
-{ echo "$as_me:$LINENO: checking for main in -lvdpau" >&5
-echo $ECHO_N "checking for main in -lvdpau... $ECHO_C" >&6; }
-if test "${ac_cv_lib_vdpau_main+set}" = set; then
+    if test "${ac_cv_header_vdpau_vdpau_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for vdpau/vdpau.h" >&5
+echo $ECHO_N "checking for vdpau/vdpau.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_vdpau_vdpau_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_vdpau_vdpau_h" >&5
+echo "${ECHO_T}$ac_cv_header_vdpau_vdpau_h" >&6; }
 else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lvdpau  $LIBS"
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking vdpau/vdpau.h usability" >&5
+echo $ECHO_N "checking vdpau/vdpau.h usability... $ECHO_C" >&6; }
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-
-
-int
-main ()
-{
-return main ();
-  ;
-  return 0;
-}
+$ac_includes_default
+#include <vdpau/vdpau.h>
 _ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (ac_try="$ac_link"
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
 case "(($ac_try" in
   *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
   *) ac_try_echo=$ac_try;;
 esac
 eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_link") 2>conftest.er1
+  (eval "$ac_compile") 2>conftest.er1
   ac_status=$?
   grep -v '^ *+' conftest.er1 >conftest.err
   rm -f conftest.er1
@@ -7739,33 +7736,106 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
   (exit $ac_status); } && {
 	 test -z "$ac_c_werror_flag" ||
 	 test ! -s conftest.err
-       } && test -s conftest$ac_exeext &&
-       $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_vdpau_main=yes
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-	ac_cv_lib_vdpau_main=no
+	ac_header_compiler=no
 fi
 
-rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_vdpau_main" >&5
-echo "${ECHO_T}$ac_cv_lib_vdpau_main" >&6; }
-if test $ac_cv_lib_vdpau_main = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBVDPAU 1
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking vdpau/vdpau.h presence" >&5
+echo $ECHO_N "checking vdpau/vdpau.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
 _ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <vdpau/vdpau.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
 
-  LIBS="-lvdpau $LIBS"
+  ac_header_preproc=no
+fi
 
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: vdpau/vdpau.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: vdpau/vdpau.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: vdpau/vdpau.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: vdpau/vdpau.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: vdpau/vdpau.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: vdpau/vdpau.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: vdpau/vdpau.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: vdpau/vdpau.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: vdpau/vdpau.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: vdpau/vdpau.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: vdpau/vdpau.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: vdpau/vdpau.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: vdpau/vdpau.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: vdpau/vdpau.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: vdpau/vdpau.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: vdpau/vdpau.h: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## ---------------------------- ##
+## Report this to bugs@xbmc.org ##
+## ---------------------------- ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for vdpau/vdpau.h" >&5
+echo $ECHO_N "checking for vdpau/vdpau.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_vdpau_vdpau_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_vdpau_vdpau_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_vdpau_vdpau_h" >&5
+echo "${ECHO_T}$ac_cv_header_vdpau_vdpau_h" >&6; }
+
+fi
+if test $ac_cv_header_vdpau_vdpau_h = yes; then
+  :
 else
   use_vdpau=no;{ echo "$as_me:$LINENO: result: $vdpau_not_found" >&5
 echo "${ECHO_T}$vdpau_not_found" >&6; }
 fi
+
 
   else
     { echo "$as_me:$LINENO: $vdpau_disabled" >&5
